# Generated by Django 3.1.7 on 2021-03-11 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/<django.db.models.fields.related.ForeignKey>/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecomm.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/<django.db.models.fields.related.ForeignKey>/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecomm.product')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecomm.product')),
            ],
        ),
    ]
