# Generated by Django 3.1.7 on 2021-03-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0002_auto_20210311_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodimage',
            name='image',
            field=models.ImageField(upload_to='media/images/None/'),
        ),
        migrations.AlterField(
            model_name='prodvideo',
            name='video',
            field=models.FileField(upload_to='media/videos/None/'),
        ),
    ]
