# Generated by Django 3.1.7 on 2021-03-11 18:01

import Ecomm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0004_auto_20210311_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodimage',
            name='image',
            field=models.ImageField(upload_to=Ecomm.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='prodvideo',
            name='video',
            field=models.FileField(upload_to=Ecomm.models.get_video_path),
        ),
    ]
