# Generated by Django 3.1.7 on 2021-03-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0006_product_new_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='primary_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prodvideo',
            name='main_video',
            field=models.BooleanField(default=False),
        ),
    ]
