# Generated by Django 3.1.7 on 2021-03-17 07:15

import Ecomm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0007_auto_20210312_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='googleplay_url',
            field=models.SlugField(default='null', max_length=200),
        ),
        migrations.CreateModel(
            name='ProdThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Ecomm.models.get_image_path)),
                ('product_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ecomm.product')),
            ],
        ),
    ]
