# Generated by Django 3.1.7 on 2021-03-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0008_auto_20210317_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='null', upload_to='prod_thumbnails'),
        ),
        migrations.DeleteModel(
            name='ProdThumbnail',
        ),
    ]
