# Generated by Django 3.1.7 on 2021-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0011_auto_20210317_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
