# Generated by Django 3.1.7 on 2021-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0013_ledimage_ledproduct_upcomingproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Careful!! : Should be same as provided in the Products model.', max_length=50)),
                ('banner', models.ImageField(upload_to='categoryBanners/')),
            ],
        ),
        migrations.AlterField(
            model_name='ledimage',
            name='image',
            field=models.ImageField(upload_to='ledImages/'),
        ),
        migrations.AlterField(
            model_name='ledproduct',
            name='led_OFF_img',
            field=models.ImageField(upload_to='ledImages/'),
        ),
        migrations.AlterField(
            model_name='ledproduct',
            name='led_ON_img',
            field=models.ImageField(upload_to='ledImages/'),
        ),
    ]
